[versions]
junitVer = "5.8.2"
selenideVer = "6.5.0"

[libraries]
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junitVer" }
selenide = { module = "com.codeborne:selenide", version.ref = "selenideVer" }
