name: Run UI Smoke Tests

on:
  workflow_dispatch:

jobs:
  test-tune:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        localization: [ us, es ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Run tests on site '${{ matrix.localization }}' l10n
        run: ./gradle smoke
        env:
          LOCALIZATION: ${{ matrix.localization }}
